// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:00:52
using Domain.Entities;
using Repositories.Core;
using System.Linq;

namespace Repositories.Interface
{
    public partial interface IArticle_CommentRepository : IRepository<Article_Comment>
    { }
}
