// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:33:52
using Domain.Entities;
using Repositories.Core;
using System.Linq;

namespace Repositories.Interface
{
    public partial interface IBookSection_CommentRepository : IRepository<BookSection_Comment>
    { }
}
