// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:04:10
using Domain.Entities;
using Repositories.Core;
using System.Linq;

namespace Repositories.Interface
{
    public partial interface IFavorite_CourseBoxRepository : IRepository<Favorite_CourseBox>
    { }
}
