// Code generated by a template
// Project: Remember
// https://github.com/yiyungent/Remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-06-26 09:48:16
using Domain.Entities;
using Repositories.Core;
using System.Linq;

namespace Repositories.Interface
{
    public partial interface IRole_MenuRepository : IRepository<Role_Menu>
    { }
}
