// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:02:53
using Domain.Entities;
using Repositories.Core;
using Repositories.Interface;

namespace Repositories.Implement
{
    public partial class Article_ParticipantRepository : BaseRepository<Article_Participant>, IArticle_ParticipantRepository
    {
        private readonly RemDbContext _context;

        public Article_ParticipantRepository(RemDbContext context) : base(context)
        {
            this._context = context;
        }
    }
}
