// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:02:53
using Domain.Entities;
using Repositories.Core;
using Repositories.Interface;

namespace Repositories.Implement
{
    public partial class Favorite_ArticleRepository : BaseRepository<Favorite_Article>, IFavorite_ArticleRepository
    {
        private readonly RemDbContext _context;

        public Favorite_ArticleRepository(RemDbContext context) : base(context)
        {
            this._context = context;
        }
    }
}
