// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:02:53
using Domain.Entities;
using Repositories.Core;
using Repositories.Interface;

namespace Repositories.Implement
{
    public partial class Follower_FollowedRepository : BaseRepository<Follower_Followed>, IFollower_FollowedRepository
    {
        private readonly RemDbContext _context;

        public Follower_FollowedRepository(RemDbContext context) : base(context)
        {
            this._context = context;
        }
    }
}
