// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:32:23
using Domain.Entities;
using Repositories.Core;
using Repositories.Interface;

namespace Repositories.Implement
{
    public partial class Sys_MenuRepository : BaseRepository<Sys_Menu>, ISys_MenuRepository
    {
        private readonly RemDbContext _context;

        public Sys_MenuRepository(RemDbContext context) : base(context)
        {
            this._context = context;
        }
    }
}
