// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:33:45
using Domain.Entities;
using Services.Core;

namespace Services.Interface
{
    public partial interface IFavorite_CardBoxService : IService<Favorite_CardBox>
    { }
}
