// Code generated by a template
// Project: Remember
// https://github.com/yiyungent/Remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-06-26 09:50:59
using Domain.Entities;
using Services.Core;

namespace Services.Interface
{
    public partial interface IFollower_FollowedService : IService<Follower_Followed>
    { }
}
