// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:05
using Domain.Entities;
using Services.Core;

namespace Services.Interface
{
    public partial interface IRole_MenuService : IService<Role_Menu>
    { }
}
