// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:36:18
using Domain.Entities;
using Services.Core;

namespace Services.Interface
{
    public partial interface IUser_BookSectionService : IService<User_BookSection>
    { }
}
