// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:48
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Article_CommentService : BaseService<Article_Comment>, IArticle_CommentService
    {
        private readonly IArticle_CommentRepository _repository;
        public Article_CommentService(IArticle_CommentRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
