// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:48
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Article_LikeService : BaseService<Article_Like>, IArticle_LikeService
    {
        private readonly IArticle_LikeRepository _repository;
        public Article_LikeService(IArticle_LikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
