// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:48
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Article_DislikeService : BaseService<Article_Dislike>, IArticle_DislikeService
    {
        private readonly IArticle_DislikeRepository _repository;
        public Article_DislikeService(IArticle_DislikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
