// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:48
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Article_ParticipantService : BaseService<Article_Participant>, IArticle_ParticipantService
    {
        private readonly IArticle_ParticipantRepository _repository;
        public Article_ParticipantService(IArticle_ParticipantRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
