// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class BookInfo_LikeService : BaseService<BookInfo_Like>, IBookInfo_LikeService
    {
        private readonly IBookInfo_LikeRepository _repository;
        public BookInfo_LikeService(IBookInfo_LikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
