// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class BookSection_CommentService : BaseService<BookSection_Comment>, IBookSection_CommentService
    {
        private readonly IBookSection_CommentRepository _repository;
        public BookSection_CommentService(IBookSection_CommentRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
