// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class BookInfo_ParticipantService : BaseService<BookInfo_Participant>, IBookInfo_ParticipantService
    {
        private readonly IBookInfo_ParticipantRepository _repository;
        public BookInfo_ParticipantService(IBookInfo_ParticipantRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
