// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class BookInfo_DislikeService : BaseService<BookInfo_Dislike>, IBookInfo_DislikeService
    {
        private readonly IBookInfo_DislikeRepository _repository;
        public BookInfo_DislikeService(IBookInfo_DislikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
