// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Comment_LikeService : BaseService<Comment_Like>, IComment_LikeService
    {
        private readonly IComment_LikeRepository _repository;
        public Comment_LikeService(IComment_LikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
