// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class CourseBox_CommentService : BaseService<CourseBox_Comment>, ICourseBox_CommentService
    {
        private readonly ICourseBox_CommentRepository _repository;
        public CourseBox_CommentService(ICourseBox_CommentRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
