// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class CourseBox_DislikeService : BaseService<CourseBox_Dislike>, ICourseBox_DislikeService
    {
        private readonly ICourseBox_DislikeRepository _repository;
        public CourseBox_DislikeService(ICourseBox_DislikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
