// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Favorite_CardBoxService : BaseService<Favorite_CardBox>, IFavorite_CardBoxService
    {
        private readonly IFavorite_CardBoxRepository _repository;
        public Favorite_CardBoxService(IFavorite_CardBoxRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
