// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Favorite_BookInfoService : BaseService<Favorite_BookInfo>, IFavorite_BookInfoService
    {
        private readonly IFavorite_BookInfoRepository _repository;
        public Favorite_BookInfoService(IFavorite_BookInfoRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
