// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Learner_CourseBoxService : BaseService<Learner_CourseBox>, ILearner_CourseBoxService
    {
        private readonly ILearner_CourseBoxRepository _repository;
        public Learner_CourseBoxService(ILearner_CourseBoxRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
