// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Learner_VideoInfoService : BaseService<Learner_VideoInfo>, ILearner_VideoInfoService
    {
        private readonly ILearner_VideoInfoRepository _repository;
        public Learner_VideoInfoService(ILearner_VideoInfoRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
