// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:48
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class LogInfoService : BaseService<LogInfo>, ILogInfoService
    {
        private readonly ILogInfoRepository _repository;
        public LogInfoService(ILogInfoRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
