// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Role_MenuService : BaseService<Role_Menu>, IRole_MenuService
    {
        private readonly IRole_MenuRepository _repository;
        public Role_MenuService(IRole_MenuRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
