// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Role_UserService : BaseService<Role_User>, IRole_UserService
    {
        private readonly IRole_UserRepository _repository;
        public Role_UserService(IRole_UserRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
