// Code generated by a template
// Project: Remember
// LastUpadteTime: 2020-06-22 05:06:48
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class SearchDetailService : BaseService<SearchDetail>, ISearchDetailService
    {
        private readonly ISearchDetailRepository _repository;
        public SearchDetailService(ISearchDetailRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
