// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Sys_MenuService : BaseService<Sys_Menu>, ISys_MenuService
    {
        private readonly ISys_MenuRepository _repository;
        public Sys_MenuService(ISys_MenuRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
