// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class User_BookInfoService : BaseService<User_BookInfo>, IUser_BookInfoService
    {
        private readonly IUser_BookInfoRepository _repository;
        public User_BookInfoService(IUser_BookInfoRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
