// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-12-03 10:35:07
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class User_BookSectionService : BaseService<User_BookSection>, IUser_BookSectionService
    {
        private readonly IUser_BookSectionRepository _repository;
        public User_BookSectionService(IUser_BookSectionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
