// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class VideoInfo_CommentService : BaseService<VideoInfo_Comment>, IVideoInfo_CommentService
    {
        private readonly IVideoInfo_CommentRepository _repository;
        public VideoInfo_CommentService(IVideoInfo_CommentRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
