// Code generated by a template
// Project: Remember
// LastUpadteTime: 2019-10-01 11:35:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class VideoInfoService : BaseService<VideoInfo>, IVideoInfoService
    {
        private readonly IVideoInfoRepository _repository;
        public VideoInfoService(IVideoInfoRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
